PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?entity ?property ?value
WHERE {
  VALUES ?property { dcterms:contributor }
  ?entity ?property ?value .
  FILTER(!regex(str(?value), "^https://github.com/orgs/[a-z-_]+/teams/") &&
         !regex(str(?value), "^(https?://orcid.org/)[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}(?:[0-9]|X)") && 
         !regex(str(?value), "^(https://www.wikidata.org/entity/Q)[0-9]+") &&
         !regex(str(?value), "^(https://ror.org/)[0-9a-z]{9}") )
}